### ISSUE TITLE
[Enhancement] Consider adding resource matching rules to the KRM-KCL Spec

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/krm-kcl#13]
## Background

In the current version of the KRM KCL specification, users need to repeatedly write and filter certain types of resource codes such as service and deployments, and consider adding resource filtering declarations to further reduce the required code volume, such as the following form.

```python
resourceRules:
 - apiGroups:   ["apps"]
   apiVersions: ["v1"]
   resources:   ["deployments"]
```

## Reference

+ Kubernetes Validating Admission Policy: https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/

**Comment by satyazzz123** [comment]
Hello @peefy can I work on this issue?

**Comment by satyazzz123** [comment]
Hello @Peefy I had a question 

>In the current version of the KRM KCL specification, users need to repeatedly write and filter certain types of resource codes such as service and deployments

How do we currently write deployments and services inside KCL , can I see some examples of where there is a typical usage of `resource code`  for deployments and services

**Comment by Peefy** [comment]
> Hello @Peefy I had a question
> 
> > In the current version of the KRM KCL specification, users need to repeatedly write and filter certain types of resource codes such as service and deployments
> 
> How do we currently write deployments and services inside KCL , can I see some examples of where there is a typical usage of `resource code` for deployments and services

Here's documents https://kcl-lang.io/docs/user_docs/guides/working-with-k8s/overview

In fact, what this issue wants to do is to filter these fields through configuration when there is a series of resource inputs on the resource transformer. https://github.com/kcl-lang/krm-kcl/blob/main/pkg/edit/transformer.go#L38

**Comment by shruti2522** [comment]
Would be happy to take this one, @Peefy

**Comment by Peefy** [comment]
Thank you! @shruti2522
