### ISSUE TITLE
[Enhancement] Support Extra KCL top level arguments for `kio.Pipeline`.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/krm-kcl#26]

**Comment by satyazzz123** [comment]
Hello @Peefy can you give me some information about this issue about what is required . Thank you!

**Comment by Peefy** [comment]
> Hello @Peefy can you give me some information about this issue about what is required . Thank you!

In this issue, we need to expand the [RunKCL](https://github.com/kcl-lang/krm-kcl/blob/main/pkg/edit/bootstrap.go#L37) function with more options just like:

```go
func RunKCL(name, source string, resourceList *yaml.RNode, arguments, []string) ([]*yaml.RNode, error) {
```

And put the `arguments` into `opts.Arguments` at [here](https://github.com/kcl-lang/krm-kcl/blob/main/pkg/edit/bootstrap.go#L140C2-L140C16)

**Comment by d4v1d03** [comment]
Hey @Peefy , can you pls assign me this issue, i want to work on it.
