### ISSUE TITLE
[Enhancement] Read the environment variables through `option("PATH")` in KRM KCL Spec

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/krm-kcl#27]

**Comment by satyazzz123** [comment]
Hello @Peefy can I give this issue a try?

**Comment by Peefy** [comment]
> Hello @Peefy can I give this issue a try?

Hello @satyazzz123. Thank you for taking note of this issue. You can directly open a PR to complete the corresponding features. If you have any questions, please feel free to contact me at any time.

**Comment by satyazzz123** [comment]
> > Hello @Peefy can I give this issue a try?
> 
> Hello @satyazzz123. Thank you for taking note of this issue. You can directly open a PR to complete the corresponding features. If you have any questions, please feel free to contact me at any time.

Thanks @Peefy . Sure,I am working on the PR

**Comment by satyazzz123** [comment]
Hello @Peefy , I had a question how is krm-kcl able to implement this logic-

`Read resources from option("resource_list"). The option("resource_list") complies with the [KRM Functions Specification](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md#krm-functions-specification). You can read the input resources from option("items") and the functionConfig from option("functionConfig").` 

How  KCL script is able to  read a list of resources from an option named like "resource_list".

**Comment by Peefy** [comment]
You can see the logic here: https://github.com/kcl-lang/krm-kcl/blob/main/pkg/edit/bootstrap.go#L108

**Comment by satyazzz123** [comment]
Thank you @Peefy , I just had a question. I found `Read the OpenAPI schema. e.g. option("open_api")["definitions"]["io.k8s.api.apps.v1.Deployment"] .` is  in not yet implemented state , if its not an issue can I open a PR to address that ?

**Comment by Peefy** [comment]
> Thank you @Peefy , I just had a question. I found `Read the OpenAPI schema. e.g. option("open_api")["definitions"]["io.k8s.api.apps.v1.Deployment"] .` is in not yet implemented state , if its not an issue can I open a PR to address that ?

Sure! Thank you!
