### ISSUE TITLE
Disable auto block pr option of contributor-assistant/github-action

### ISSUE THREAD

**Issue by liangyuanpeng** [kcl-lang/krm-kcl#41]
## Enhancement

Partof https://github.com/kcl-lang/community/issues/18

This is suitable for `good first issue`

**Comment by d4v1d03** [comment]
Hey @Peefy , can you assign me this ?

**Comment by liangyuanpeng** [comment]
resolved by https://github.com/kcl-lang/krm-kcl/pull/48
