### ISSUE TITLE
[Enhancement] Resources selection

### ISSUE THREAD

**Issue by dennybaa** [kcl-lang/krm-kcl#53]
Hello @Peefy, thanks for developing such awesome stuff first of all. I've got a question...

As I can see you use KRM function spec for KCL, I'm very new to all these tech. But I can see that from the perspective of helm, kubectl or helmfile when used together with KCL the selected resources are evidently scooped to the list of applied manifests or the applied chart. 

Here's the question which is more relevant to KCL operator scenorio, but generally could be useful for every plugin which uses KCLRun. Looks like KCLRun CRD could provide some sort of match labels and api type selectors to be able to selectively apply KCL function. Otherwise KCL function is applied to all resources and filtering becomes part of every and each kcl function... This seems to be an overhead and complexity, which could be diminished if there were selectors. What's your point on this issue?

**Comment by Peefy** [comment]
Yes. I agree. This issue is what you want? https://github.com/kcl-lang/krm-kcl/issues/13

**Comment by Peefy** [comment]
Hello @dennybaa Are you interested in contributing it? According to the plan, we may impl it by mid May.

**Comment by Peefy** [comment]
Closed by https://github.com/kcl-lang/krm-kcl/pull/54 Thanks for the great job! @shruti2522
